version: "3.9"
volums:
  http-html-data:
services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - http-html-data:/var/www/html

  apache-httpd:
    build:
      context: .
      dockerfile: ./apache/Dockerfile
    volumes:
      - http-html-data:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - php-fpm
